name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # Your EC2 instance's public IP
          username: ubuntu  # The SSH username for your EC2 instance
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Reference to SSH private key stored in GitHub Secrets
          script: |
            cd /home/ubuntu/wanderlust  # Replace with the path where your Docker-compose files are located on your EC2 instance
            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml up -d
